version: "3"

services:
  openttd-server:
    image: redditopenttd/openttd:latest
    expose:
      - "3979/tcp"
      - "3979/udp"
    user: openttd
    volumes:
      - ./.openttd/openttd.cfg:/config/openttd.cfg:ro
  openttd-client:
    build: ./openttd-client
    expose:
      - "5901/tcp"
    user: openttd
    volumes:
      - ./.openttd/openttd.cfg:/home/openttd/.openttd/openttd.cfg:ro
      - ./openttd-client/.vnc/xstartup:/.vnc/xstartup:ro
  js-server:
    build: ./server
    ports:
      - "3000/tcp"
    user: node
